"""Dropfans integration package.

Dropfans is the sole active external commerce / vault / payment provider.
Fangate remains in the repository as legacy/deferred code only.
"""

from .errors import (
    DropfansAuthenticationError,
    DropfansAuthorizationError,
    DropfansError,
    DropfansNotFoundError,
    DropfansRateLimitError,
    DropfansResponseError,
    DropfansServerError,
    DropfansTimeoutError,
    DropfansTransportError,
    DropfansValidationError,
)
from .models import (
    DropfansAccount,
    DropfansBalance,
    DropfansDrop,
    DropfansDropMediaItem,
    DropfansDropResult,
    DropfansEarnings,
    DropfansEarningsChart,
    DropfansEarningsStats,
    DropfansEarningsTransaction,
    DropfansEarningsTypeTotal,
    DropfansLinks,
    DropfansNotifications,
    DropfansPost,
    DropfansPostCreateResult,
    DropfansPostLimits,
    DropfansPostListResult,
    DropfansPostMedia,
    DropfansSaleStatus,
    DropfansTelegramLinks,
    DropfansVaultFolder,
    DropfansVaultItem,
    DropfansVaultListResult,
    DropfansVaultUploadResult,
    DropfansVideoStatus,
    DropfansVideoUploadComplete,
    DropfansVideoUploadStart,
    DropfansWebLinks,
)
from .security import (
    DropfansCredentialVault,
    decrypt_secret,
    encrypt_secret,
    get_vault,
)

__all__ = [
    "DropfansAccount",
    "DropfansAuthenticationError",
    "DropfansAuthorizationError",
    "DropfansBalance",
    "DropfansDrop",
    "DropfansDropMediaItem",
    "DropfansDropResult",
    "DropfansEarnings",
    "DropfansEarningsChart",
    "DropfansEarningsStats",
    "DropfansEarningsTransaction",
    "DropfansEarningsTypeTotal",
    "DropfansError",
    "DropfansLinks",
    "DropfansNotFoundError",
    "DropfansNotifications",
    "DropfansPost",
    "DropfansPostCreateResult",
    "DropfansPostLimits",
    "DropfansPostListResult",
    "DropfansPostMedia",
    "DropfansRateLimitError",
    "DropfansResponseError",
    "DropfansSaleStatus",
    "DropfansServerError",
    "DropfansTelegramLinks",
    "DropfansTimeoutError",
    "DropfansTransportError",
    "DropfansValidationError",
    "DropfansVaultFolder",
    "DropfansVaultItem",
    "DropfansVaultListResult",
    "DropfansVaultUploadResult",
    "DropfansVideoStatus",
    "DropfansVideoUploadComplete",
    "DropfansVideoUploadStart",
    "DropfansWebLinks",
    "DropfansCredentialVault",
    "decrypt_secret",
    "encrypt_secret",
    "get_vault",
]
