"""Generate P3.1 test file."""
import pathlib

lines = []
a = lines.append

a('"""P3.1 - LLM Context Enrichment Tests."""')
a('')
a('from datetime import UTC, datetime, timedelta')
a('from unittest.mock import AsyncMock, patch')
a('')
a('import pytest')
a('')
a('pytestmark = [pytest.mark.unit]')
a('')
a('')
a('def _user_row(**overrides):')
a('    base = {')
a('        "id": 12345, "username": "testuser", "first_name": "Alice",')
a('        "message_count": 10, "funnel_stage": "new",')
a('        "is_blocked": False, "do_not_auto_reply": False,')
a('    }')
a('    base.update(overrides)')
a('    return base')
a('')
a('')
a('def _patches(user=None, msgs=None, summary=None,')
a('             purchases=(0, []), offers=(False, None),')
a('             product=(None, None, None, None),')
a('             creator=(None, False),')
a('             last_purchase=None, last_followup=None):')
a('    u = user or _user_row()')
a('    m = msgs if msgs is not None else []')
a('    return [')
a('        patch("memory.context_assembler._get_user_safe", new_callable=AsyncMock, return_value=u),')
a('        patch("memory.context_assembler._get_recent_messages_safe", new_callable=AsyncMock, return_value=m),')
a('        patch("memory.context_assembler._get_summary_safe", new_callable=AsyncMock, return_value=summary),')
a('        patch("memory.context_assembler._get_purchases_safe", new_callable=AsyncMock, return_value=purchases),')
a('        patch("memory.context_assembler._get_active_offers_safe", new_callable=AsyncMock, return_value=offers),')
a('        patch("memory.context_assembler._get_product_info_safe", new_callable=AsyncMock, return_value=product),')
a('        patch("memory.context_assembler._get_creator_info_safe", new_callable=AsyncMock, return_value=creator),')
a('        patch("memory.context_assembler._get_last_purchase_at_safe", new_callable=AsyncMock, return_value=last_purchase),')
a('        patch("memory.context_assembler._get_last_followup_at_safe", new_callable=AsyncMock, return_value=last_followup),')
a('    ]')
a('')
a('')
a('async def _build(**kw):')
a('    from memory.context_assembler import build_llm_context')
a('    ps = _patches(**{k: kw[k] for k in kw if k in _patches.__code__.co_varnames})')
a('    cid = kw.pop("creator_id", 1)')
a('    uid = kw.pop("user_id", 12345)')
a('    for p in ps:')
a('        p.start()')
a('    try:')
a('        return await build_llm_context(cid, uid)')
a('    finally:')
a('        for p in ps:')
a('            p.stop()')

pathlib.Path('tests/test_context_assembler.py').write_text('\n'.join(lines), encoding='utf-8')
print(f"Wrote {len(lines)} lines")
