"""V2 services (Phase 2+). Application logic; LLM never writes state directly."""

from relationship_v2.services.absence_service import (
    BRIEF_ABSENCE_DAYS,
    LONG_ABSENCE_DAYS,
    AbsenceBand,
    ReturnPlan,
    classify_absence,
    plan_return,
)
from relationship_v2.services.activation import (
    activate,
    check_preconditions,
    deactivate,
    dependencies_ok,
    is_active_for_scope,
)
from relationship_v2.services.backfill import (
    BackfillReport,
    flatten_knowledge_items,
    flatten_profile_facts,
    run_backfill,
)
from relationship_v2.services.commerce_adapter import (
    COMMERCE_SNAPSHOT_TTL_SECONDS,
    build_action_request,
    build_purchase_feedback,
    confirmation_payload_hash,
    map_confirmation,
    map_error_to_strategy,
)
from relationship_v2.services.commerce_adapter import (
    is_snapshot_stale as is_commerce_snapshot_stale,
)
from relationship_v2.services.commerce_adapter import (
    read_context as read_commerce_context,
)
from relationship_v2.services.commerce_adapter import (
    record_confirmed as record_commerce_confirmed,
)
from relationship_v2.services.commerce_adapter import (
    record_requested as record_commerce_requested,
)
from relationship_v2.services.context_assembly import (
    COMPOSITION_ORDER,
    DROP_ORDER,
    SECTION_BUDGETS,
    TOTAL_BUDGET_CHARS,
    assemble,
    resolve_conflicts,
)
from relationship_v2.services.contradiction_resolver import (
    ConflictKind,
    ConflictRecord,
    ConflictResolution,
    resolve_conflict,
)
from relationship_v2.services.conversation_engine import (
    TurnOutcome,
    TurnResult,
    apply_turn,
    classify_inbound,
    derive_topic,
    load_conversation_state,
    resume_context,
    transition_conversation,
)
from relationship_v2.services.dossier import Dossier, DossierSection, build_dossier
from relationship_v2.services.episode_manager import (
    EpisodePlan,
    plan_candidates,
    plan_episode,
)
from relationship_v2.services.escalation import (
    COOLDOWN_AFTER_REJECTION_SECONDS,
    COOLDOWN_AFTER_STALL_SECONDS,
    is_cooling_down,
    is_valid_escalation_transition,
    record_strategy_change,
    select_stage,
)
from relationship_v2.services.event_processor import (
    PROCESSOR_NAME,
    ProcessorOutcome,
    ProcessResult,
    process_event,
    route_event,
)
from relationship_v2.services.intimate_history import IntimatePlan, plan_intimate
from relationship_v2.services.llm_observation import (
    MemoryObservation,
    ObservationBatch,
    ObservationDisposition,
    ObservationReport,
    ObservationResult,
    PatternObservation,
    review_batch,
)
from relationship_v2.services.memory_extraction import (
    EXTRACTOR_VERSION,
    MemoryCandidate,
    extract_candidates,
)
from relationship_v2.services.memory_retrieval import (
    RetrievalBudget,
    RetrievalResult,
    callback_score,
    retrieve_tiered,
    score_episode,
    score_fact,
)
from relationship_v2.services.memory_validation import (
    ValidationCode,
    ValidationVerdict,
    is_valid_memory_status_transition,
    validate_fact_candidate,
)
from relationship_v2.services.migration_validator import (
    LegacyFact,
    MigrationDecision,
    MigrationDisposition,
    MigrationReport,
    validate_batch,
    validate_legacy_fact,
)
from relationship_v2.services.open_loops import (
    LoopOutcome,
    LoopResult,
    is_due,
    transition_loop,
)
from relationship_v2.services.pattern_learning import (
    PatternAssessment,
    PatternLeaning,
    PatternStatus,
    assess_pattern,
    decayed_evidence,
)
from relationship_v2.services.post_send import (
    PostSendOutcome,
    PostSendResult,
    apply_response_sent,
)
from relationship_v2.services.proactive_recall import (
    RecallCandidate,
    RecalledItem,
    RecallSelection,
    rank_candidates,
    recency_decay,
    score_candidate,
)
from relationship_v2.services.queue import (
    BACKOFF_MAX_SECONDS,
    LOCK_TTL_SECONDS,
    MAX_REPLAY_ATTEMPTS,
    acquire_scope_lock,
    backoff_seconds,
    enqueue_validated_turn,
    is_stale_memory_write,
    lock_key,
    record_turn_failure,
    release_scope_lock,
    should_replay,
)
from relationship_v2.services.relationship_context import (
    SNAPSHOT_TTL_SECONDS,
    build_reentry,
    derive_comfort,
    derive_familiarity,
    derive_lifecycle,
    is_snapshot_stale,
    load_relationship_context,
)
from relationship_v2.services.relationship_derivations import (
    derive_engagement,
    derive_intimacy_trajectory,
    derive_reciprocity,
    find_due_loops,
)
from relationship_v2.services.relationship_reasoning import (
    RelationshipReading,
    StoreCounts,
    derive_continuity,
    reason_about,
)
from relationship_v2.services.replay import (
    ReplayMessage,
    normalize_message,
    order_for_replay,
    replay_key,
    text_hash,
    to_fan_received,
)
from relationship_v2.services.replay_job import ReplayReport, run_replay
from relationship_v2.services.response_engine import (
    build_plan,
    generate,
    interpret,
    next_outbound_state,
    plan_hash,
    record_generation,
    validate_response,
)
from relationship_v2.services.retirement import check_readiness, plan_removal
from relationship_v2.services.semantic_retrieval import (
    EmbeddingPort,
    FusedHit,
    embed_query,
    fuse_scores,
    rerank,
)
from relationship_v2.services.shadow import (
    compare_with_legacy,
    observe_turn,
)
from relationship_v2.services.shadow_harness import (
    ComparedTurn,
    ShadowMetrics,
    ShadowSummary,
    compare_turn,
)
from relationship_v2.services.summary import SUMMARY_BUDGET_CHARS, Summary, build_summary
from relationship_v2.services.turn_context import TurnContext, assemble_turn_context
from relationship_v2.services.turn_guard import GuardResult, run_guarded
from relationship_v2.services.turn_orchestrator import (
    InboundOutcome,
    InboundTurnResult,
    run_inbound_turn,
)

__all__ = [
    "BACKOFF_MAX_SECONDS",
    "BRIEF_ABSENCE_DAYS",
    "COMMERCE_SNAPSHOT_TTL_SECONDS",
    "COMPOSITION_ORDER",
    "COOLDOWN_AFTER_REJECTION_SECONDS",
    "COOLDOWN_AFTER_STALL_SECONDS",
    "DROP_ORDER",
    "EXTRACTOR_VERSION",
    "LOCK_TTL_SECONDS",
    "LONG_ABSENCE_DAYS",
    "MAX_REPLAY_ATTEMPTS",
    "PROCESSOR_NAME",
    "SECTION_BUDGETS",
    "SNAPSHOT_TTL_SECONDS",
    "SUMMARY_BUDGET_CHARS",
    "TOTAL_BUDGET_CHARS",
    "AbsenceBand",
    "BackfillReport",
    "ComparedTurn",
    "ConflictKind",
    "ConflictRecord",
    "ConflictResolution",
    "Dossier",
    "DossierSection",
    "EmbeddingPort",
    "EpisodePlan",
    "FusedHit",
    "GuardResult",
    "InboundOutcome",
    "InboundTurnResult",
    "IntimatePlan",
    "LegacyFact",
    "LoopOutcome",
    "LoopResult",
    "MemoryCandidate",
    "MemoryObservation",
    "MigrationDecision",
    "MigrationDisposition",
    "MigrationReport",
    "ObservationBatch",
    "ObservationDisposition",
    "ObservationReport",
    "ObservationResult",
    "PatternAssessment",
    "PatternLeaning",
    "PatternObservation",
    "PatternStatus",
    "PostSendOutcome",
    "PostSendResult",
    "ProcessResult",
    "ProcessorOutcome",
    "RecallCandidate",
    "RecallSelection",
    "RecalledItem",
    "RelationshipReading",
    "ReplayMessage",
    "ReplayReport",
    "RetrievalBudget",
    "RetrievalResult",
    "ReturnPlan",
    "ShadowMetrics",
    "ShadowSummary",
    "StoreCounts",
    "Summary",
    "TurnContext",
    "TurnOutcome",
    "TurnResult",
    "ValidationCode",
    "ValidationVerdict",
    "acquire_scope_lock",
    "activate",
    "apply_response_sent",
    "apply_turn",
    "assemble",
    "assemble_turn_context",
    "assess_pattern",
    "backoff_seconds",
    "build_action_request",
    "build_dossier",
    "build_plan",
    "build_purchase_feedback",
    "build_reentry",
    "build_summary",
    "callback_score",
    "check_preconditions",
    "check_readiness",
    "classify_absence",
    "classify_inbound",
    "compare_turn",
    "compare_with_legacy",
    "confirmation_payload_hash",
    "deactivate",
    "decayed_evidence",
    "dependencies_ok",
    "derive_comfort",
    "derive_continuity",
    "derive_engagement",
    "derive_familiarity",
    "derive_intimacy_trajectory",
    "derive_lifecycle",
    "derive_reciprocity",
    "derive_topic",
    "embed_query",
    "enqueue_validated_turn",
    "extract_candidates",
    "find_due_loops",
    "flatten_knowledge_items",
    "flatten_profile_facts",
    "fuse_scores",
    "generate",
    "interpret",
    "is_active_for_scope",
    "is_commerce_snapshot_stale",
    "is_cooling_down",
    "is_due",
    "is_snapshot_stale",
    "is_stale_memory_write",
    "is_valid_escalation_transition",
    "is_valid_memory_status_transition",
    "load_conversation_state",
    "load_relationship_context",
    "lock_key",
    "map_confirmation",
    "map_error_to_strategy",
    "next_outbound_state",
    "normalize_message",
    "observe_turn",
    "order_for_replay",
    "plan_candidates",
    "plan_episode",
    "plan_hash",
    "plan_intimate",
    "plan_removal",
    "plan_return",
    "process_event",
    "rank_candidates",
    "read_commerce_context",
    "reason_about",
    "recency_decay",
    "record_commerce_confirmed",
    "record_commerce_requested",
    "record_generation",
    "record_strategy_change",
    "record_turn_failure",
    "release_scope_lock",
    "replay_key",
    "rerank",
    "resolve_conflict",
    "resolve_conflicts",
    "resume_context",
    "retrieve_tiered",
    "review_batch",
    "route_event",
    "run_backfill",
    "run_guarded",
    "run_inbound_turn",
    "run_replay",
    "score_candidate",
    "score_episode",
    "score_fact",
    "select_stage",
    "should_replay",
    "text_hash",
    "to_fan_received",
    "transition_conversation",
    "transition_loop",
    "validate_batch",
    "validate_fact_candidate",
    "validate_legacy_fact",
    "validate_response",
]
