"""V2 persistence: owners + repository entry points (Phase 1)."""

from relationship_v2.persistence.owners import TABLE_OWNERS
from relationship_v2.persistence.repository import (
    close_open_loop,
    count_current_facts,
    count_episodes,
    count_events,
    create_commerce_ref,
    create_conversation,
    create_conversation_turn,
    create_memory_episode,
    create_memory_fact,
    create_open_loop,
    create_relationship_event,
    get_or_create_relationship,
    is_event_processed,
    list_active_loops,
    list_current_facts,
    list_intimate_history,
    list_recent_episodes,
    list_signals,
    mark_event_processed,
    mark_loop_referenced,
    record_engagement_signal,
    record_intimate_signal,
    resolve_open_loop,
    search_facts_semantic,
    set_fact_embedding,
    supersede_memory_fact,
)

__all__ = [
    "TABLE_OWNERS",
    "close_open_loop",
    "count_current_facts",
    "count_episodes",
    "count_events",
    "create_commerce_ref",
    "create_conversation",
    "create_conversation_turn",
    "create_memory_episode",
    "create_memory_fact",
    "create_open_loop",
    "create_relationship_event",
    "get_or_create_relationship",
    "is_event_processed",
    "list_active_loops",
    "list_current_facts",
    "list_intimate_history",
    "list_recent_episodes",
    "list_signals",
    "mark_event_processed",
    "mark_loop_referenced",
    "record_engagement_signal",
    "record_intimate_signal",
    "resolve_open_loop",
    "search_facts_semantic",
    "set_fact_embedding",
    "supersede_memory_fact",
]
